language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
cache:
  directories:
    - $HOME/.composer/cache
    
allow_failures:
  - php: hhvm
  - php: nightly
  
before_script:
  - composer install
